sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.organization=${SONAR_ORG}
sonar.sources=server,client/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js,**/*.test.js,**/coverage/**
sonar.tests=server/test,client/src
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info