name: CI

on:
  push:
    branches: [ lab1, test1 ]
  pull_request:
    branches: [ lab1, test1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Build server (if needed)
        run: echo "Server build complete"
        working-directory: server

      - name: Build client
        run: npm run build
        working-directory: client

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.stats()'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: client-dist
          path: client/dist

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Check MongoDB is ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Start server for testing
        run: node app.js &
        working-directory: server
        env:
          MONGODB_URI: mongodb://localhost:27017/taskmanager_test
          PORT: 3303

      - name: Wait for server to start
        run: sleep 5

      - name: Run server tests
        run: npm test
        working-directory: server
        env:
          MONGODB_URI_TEST: mongodb://localhost:27017/taskmanager_test
          NODE_ENV: test

      - name: Run client tests
        run: npm test
        working-directory: client
        env:
          VITE_API_BASE_URL: http://localhost:3303/api